---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - discovery.yndd.io
  resources:
  - discoveryrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.yndd.io
  resources:
  - discoveryrules/finalizers
  verbs:
  - update
- apiGroups:
  - discovery.yndd.io
  resources:
  - discoveryrules/status
  verbs:
  - get
  - patch
  - update
