apiVersion: discovery.yndd.io/v1alpha1
kind: DiscoveryRule
metadata:
  name: dr1
  namespace: ndd-system
spec:
  period: 1m
  enabled: true
  protocol: gnmi
  credentials: dr1-credentials
  # ip-range
  ipRange:
    cidrs: 
      - 172.20.20.0/24
    excludes:
      - 172.20.20.0/32
      - 172.20.20.1/32
      - 172.20.20.255/32
    concurrentScans: 10

