apiVersion: discovery.yndd.io/v1alpha1
kind: DiscoveryRule
metadata:
  name: dr2
  namespace: ndd-system
spec:
  period: 1m
  enabled: true
  insecure: true
  protocol: gnmi
  credentials: dr1-credentials
  target-template:
    labels:
      "yndd.io/certificate-profile": "cert-profile-2"
  ip-range: 
    cidrs:
      - 172.100.100.3/32
      - 172.100.100.4/32
      - 172.100.100.5/32


